services:
  database:
    container_name: jeilu-bd
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
      - ./backend-jeylu/.env
    volumes:
      - jeilu-db:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - jeilu-net

  backend:
    container_name: backend_jeilu
    build:
      context: ./backend-jeylu
      dockerfile: Dockerfile
    env_file:
      - ./backend-jeylu/.env
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    networks:
      - jeilu-net

  frontend:
    container_name: frontend_jeilu
    build:
      context: ./fronted-jeylu
      dockerfile: Dockerfile
    volumes:
      - frontend_dist:/app/dist
    env_file:
      - ./fronted-jeylu/.env
    restart: on-failure
    networks:
      - jeilu-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/erick/ssl:/etc/nginx/ssl:ro
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    depends_on:
      - database
      - backend
      - frontend
    networks:
      - jeilu-net

networks:
  jeilu-net:
    driver: bridge

volumes:
  jeilu-db:
  frontend_dist:
