services:
  database:
    container_name: jeilu-bd
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - jeilu-db:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - jeilu-net

  backend:
    container_name: backend_jeilu
    image: erickaguilarwda/jeylu-backend:1.0
    build:
      context: ./backend-jeylu
      dockerfile: ../Dockerfile.backend
    env_file:
      - .env
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    networks:
      - jeilu-net

  frontend:
    container_name: frontend_jeilu
    image: erickaguilarwda/jeylu-frontend:1.0
    build:
      context: ./fronted-jeylu
      dockerfile: ../Dockerfile.frontend
    env_file:
      - .env
    restart: on-failure
    networks:
      - jeilu-net

networks:
  jeilu-net:
    external: true

volumes:
  jeilu-db:
