server {
    listen 80;
    server_name erickaguilargomez.me www.erickaguilargomez.me;

    # Redirigir todo HTTP a HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name erickaguilargomez.me www.erickaguilargomez.me;

    ssl_certificate /etc/nginx/ssl/erickaguilargomez.crt;
    ssl_certificate_key /etc/nginx/ssl/erickaguilargomez.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Reenviar /api a Laravel
    location /api {
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;
    }

    # Servir Vue
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ~ /\.ht {
        deny all;
    }
}

