server {
    listen 80;
    server_name localhost;

    # 1. Reenviar todo lo que sea /api a Laravel
    location /api {
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;
    }

    # 2. Servir los archivos estáticos de Vue
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location ~ /\.ht {
        deny all;
    }
}
